### ISSUE TITLE
Rotation added Twice

### ISSUE THREAD

**Issue by Vesprawn** [miguelcobain/ember-leaflet-rotated-marker#2]
When adding rotationAngle to marker layer it adds rotateZ twice to the transform which causes the object to be rotated twice. 

    transform: translate3d(666px, 318px, 0px) rotateZ(0.1deg) rotateZ(0.1deg);

Example a 90 rotation turns into 180.

**Comment by miguelcobain** [comment]
Couldn't reproduce this. Please try version `0.1.0` and reopen if issue persists.
